const PRODUCTS = [
  { id: 1, slug: "milky-coated", name: "Milky Coated Popcorn", category: "Sweet & creamy", description: "Light, crisp popcorn folded through a silky milk coating for a melt-in-your-mouth finish.", note: "A gentle, creamy crowd-pleaser.", image: "./popcorn-milky-coated.svg", prices: { Small: 1000, Medium: 1500, Large: 3000 } },
  { id: 2, slug: "caramel", name: "Golden Caramel Popcorn", category: "Sweet & buttery", description: "A deep buttery caramel glaze with the kind of crunch that makes one handful become three.", note: "Rich caramel, made for movie nights.", image: "./popcorn-caramel.svg", prices: { Small: 1000, Medium: 1500, Large: 3000 } },
  { id: 3, slug: "plain-salted", name: "Plain Salted Popcorn", category: "Simply salted", description: "No fuss, just freshly popped kernels with a touch of salt and plenty of honest crunch.", note: "The everyday essential.", image: "./popcorn-plain.svg", prices: { Small: 600, Medium: 1000, Large: 2000 } },
  { id: 4, slug: "butter", name: "Butter Popcorn", category: "Warm & classic", description: "A classic buttery batch with a warm, savoury aroma that fills the room before you open the bag.", note: "Warm, familiar and generously buttery.", image: "./popcorn-butter.svg", prices: { Small: 600, Medium: 1000, Large: 2000 } },
  { id: 5, slug: "coconut-crunch", name: "Coconut Crunch Popcorn", category: "Toasty & sweet", description: "A sunny mix of toasted coconut and sweet crunch, made for slow afternoons and soft playlists.", note: "Toasted coconut in every bite.", image: "./popcorn-milky-coated.svg", prices: { Small: 1200, Medium: 1800, Large: 3500 } },
  { id: 6, slug: "ginger-spice", name: "Ginger Spice Popcorn", category: "Warmly spiced", description: "A little ginger warmth, a little sweetness and a whole lot of crackle. It wakes up the snack table.", note: "A bright, warming twist.", image: "./popcorn-caramel.svg", prices: { Small: 1200, Medium: 1800, Large: 3500 } },
  { id: 7, slug: "chilli-lime", name: "Chilli Lime Popcorn", category: "Zesty & bold", description: "Tangy lime leads, then a gentle chilli kick arrives. Bright, playful and surprisingly moreish.", note: "A little heat, a lot of zing.", image: "./popcorn-plain.svg", prices: { Small: 1200, Medium: 1800, Large: 3500 } },
  { id: 8, slug: "party-mix", name: "Naija Party Mix", category: "Shareable mix", description: "A cheerful blend of our favourite sweet and savoury popcorn for birthdays, visits and every kind of gathering.", note: "Made for passing around.", image: "./popcorn-butter.svg", prices: { Small: 1500, Medium: 2500, Large: 4500 } }
];
